/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "<<region>>",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "<<graphql_api_endpoint",
    "aws_appsync_region": "<<region>>",
    "aws_cognito_identity_pool_id": "<<cognito_identity_pool_id",
    "aws_cognito_region": "<<region>>",
    "aws_user_pools_id": "<<cognito_identity_pool_id>>",
    "aws_user_pools_web_client_id": "<<cognito_userpool_client_id",
    "oauth": {},
    "aws_user_files_s3_bucket": "<<s3_bucket>>",
    "aws_user_files_s3_bucket_region": "<<region>>"
};

export default awsmobile;
